### ISSUE TITLE
"Last Login" column sorts Alphabetically

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1061]
I guess no one has used this feature before.  
When you click the 'Last Login' header on http://burlesque-expo.com/profile/manage the users are sorted by that column -- but that column is treated as text and sorted alphabetically (so "April 11, 2017" comes first)

**Comment by bethlakshmi** [comment]
This was not an easy fix... I thought it would be, because there's a cool date sorter - https://datatables.net/blog/2014-12-18 - for our datatables, but the formats it provides and the formats we are using are not so compatible.  Leaving this note as this was a low priority so not worth tons of time.

**Comment by burlexpo** [comment]
Ok -- it's kind of annoying as it also effects things like the Act Review page.

**Comment by bethlakshmi** [comment]
Fixed in Divio
