### ISSUE TITLE
ASAP: Changes to Act Review (content)

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1113]
This replaces the two drop-down voting system we use now and lets us use a simple points based system.

The Review committee should be able to rate each act in each of the following categories using a dropdown menu with the following options: --, 0, 1, 2, 3, 4, 5.  The default is "--".

The categories are:

- Costuming
- Creatvity
- Essay
- R.O.I.
- Stage Presence.
- Technical Merit
- Video

**Comment by bethlakshmi** [comment]
Yes, I can do that... it would require me to:
 - create a new database table or two to hold the category and the rating - I'd probably make the categories fluid, so you can change them w/out bugging me.
 - link that up and display a specialized form for act reviewing that gives the reviewer the abilty to reiew
 - need to change the review table on:  http://www.burlesque-expo.com/act/reviewlist to show this data.

Thoughts/questions:
- do you still want a comment area or does this imply that I would REMOVE the freeform text field (Personally, I think it's useful and should stay, but you are the boss).

- to make the review summaries readable, I suggest:
   - make the column that says "reviews" show ONLY who has reviewed so far (so it's really "reviewed by", where the table cell says "Scratch, Scartlet Letter, Betty Blaize", etc) so you can just see how many reviewers have reviewed
   - make EITHER:
   (A) - an expandable row, that the expanded row gives all the details of what # each reviewer gave each category.
  (B) - put all the review details on the act review page, so that the coordinator clicks on "review" and all the data is right there next to the form for accept/reject).

Trying to scrunch all the data into table form will be hellish.

**Comment by bethlakshmi** [comment]
Betty Estimate - 8 pts.  Done this sort of thing before, path is clear.  Time is not short, more like 2 weeks than 1 week.  But not killer long.
