### ISSUE TITLE
ASAP: Changes to http://www.burlesque-expo.com/act/reviewlist

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1114]
1) Hide "Last Update Column" as default
2) Remove "Review" column
3) If possible, rotate header of column "Action" 90°, and replace word "Review" with a single icon button; a combination of http://simplelineicons.com/icon-like and http://simplelineicons.com/icon-dislike would work.
4) Add new columns as follows.  SInce each of these is going to be one column, this layout is predicated on the ability to rotate header text 90°.  If we can't we're going to have to figure something else out:
- Costuming
- Creativity
- Essay
- Experience 
- R.O.I.
- Stage Presence.
- Technical Merit
- Video

where each of these *except experience* is an average of the scores of the reviewers.  "Experience" is a simple numeric value taken from "Years of experience" from the bidder's Stage Persona.

**Comment by bethlakshmi** [comment]
1 & 2 - easy peasy (lemon squeezy)

3 - action review 90 degrees - I think that will make a big, thick ugly header that consumes a lot of real estate.  I can do it:
https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_transform

On the buttons - yep, no problem!  I sounds like you want a thumbs-up and a thumbs down side by side on one button, right?  easy peasy

4 - Essentially what you want is that I take the Review column and the action column and replace the ~400px that they consume on a regular screen with 9 columns, all vertically rotated headers (action + new 8 categories).  Since each is definitely less than 25 px, it should result in much thinner rows (yay) at the expense of a very thick header (meh).

Hmm... I played around in a prototype-y way and while I can make the text rotate by 90 degrees, I can not make both rotate by 90 degrees AND not look hideous.  There is surely some way to do it... but that way is not immediately obvious.

I do think I can either manage, OR talk you into something that does the same thing space wise without being exactly that ... for example - a single letter or two with hover text (Co, Cr, Es, Ex, R, SP, TM, V, A) 

If I figure that part out easily, the hardest part is remapping the bid table to show the new review data.  And that's no so bad - maybe 1 week.

**Comment by burlexpo** [comment]
@bethlakshmi  Tested http://gbeadmin.webfactional.com/admin/gbe/evaluationcategory/? I made some changes -- turned "Technical Merit" invisible and added the help text "This is now invisible"; added the category "Pickles".  

Changes did *not* take on the one act I had reviewed already (http://gbeadmin.webfactional.com/act/review/962) but did show up on acts which no one had yet reviewed (i.e. http://gbeadmin.webfactional.com/act/review/966)

**Comment by bethlakshmi** [comment]
I addressed the above comment, and added a Notes field as well, with a display on the review act page.  Resynced on gbeadmin.webfactional.com
