### ISSUE TITLE
Remove WebDev from Act Review email alias

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1116]
Every time a new act comes in, it generates an email.  For a while we weren't sure that was happening so we added WebDev to the list of people who are supposed to get act notifications.  I'm convinced the email is going out as it's supposed to.  Let's remove WebDev (and @bethlakshmi) from the list of people who get email everytime an act is submitted.  It'll also keep me from getting two or more copies of every notification.

**Comment by bethlakshmi** [comment]
I read the code and this wasn't a code change - it was a configuration change.  We had TWO accounts for webdev@burlesque-expo.com in the users of the site.  One of those 2 accounts was in every privileged group in the system, so it was an Act/Class/Volunteer/etc. Reviewer and rightfully getting all that email.  

Since there were 2 webdev accounts in the system, I removed the overly priviledged one (gbeadmin) and left the other alone (gbelive).  The email to webdev should stop as of now.

That doesn't fix the email problem for *me* - because I do have Betty's account, and it's also a reviewer of everything.  For me, personally, it's just too useful, so I'm leaving it.

NOTE- this was to remove email being sent TO webdev.  Not email being sent FROM webdev - that is absolutely still happening, and worth a separate ticket because webdev is not really the right email sender for almost anything -- in most cases it should be the appropriate bid coordinator.
