### ISSUE TITLE
Improvements to http://www.burlesque-expo.com/act/reviewlist 

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1154]
1) No one understands the "Thumbs Up/Down" button.  Can we just change it to the word "Review"?

2) When an act reviewer goes to the Act Review page, is there a way to indicate which acts they personally have reviewed? Either by changing the color of the text or added a "Done?" column with a checkmark for the done ones.  Obviously, the results for this would be different for each act reviewer who looks at it and it would change after they reviewed an act.

**Comment by bethlakshmi** [comment]
1 - OK.  I will always dislike words over pictures because they take more space.  But a word makes sense here.  Change is easy.

2  - We talked yesterday, it sounded like color coding could be a good plan.  And I just figured out how to make that work on another ticket.  How about we use:
- green for anything that just recently succeeded - for example, when you've successfully reviewed an event.
- red - for anything that failed.   I can't think of how event review would fail, but let's just reserve that color.
- ? blue? - fpr the stuff you should do.

so... blue items would be the "here, review this" color.

That said...   a color is not sortable.  If you thought it was useful for them to sort on the  Reviewed? yes or no value, then maybe we want a data column as well.
