### ISSUE TITLE
Email schedules morning of BurlExpo

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#1184]
Can we email each individual their own personal schedule at 10:00pm the night before? i.e., at 10:00pm on Thursday night, I get an email detailing what my schedule is for Friday.

**Comment by bethlakshmi** [comment]
Do you want this to be triggered manually (pretty easy) or automatically (doable, a bit more work).

Either way, I think the logic is:
- get the list all active users
- from that list, look up each person's schedule for tomorrow.  If the person has nothing on their schedule, they don't get an email.
- compile a list that looks like our printed schedules
- add some subject matter from a message stored in our database (that way it's configurable)
- mail an email to that user's email.

I'd be happy to assume that users who bought tickets *don't* get an email just because they bought a ticket, right?  For example, if I bought a Main Event ticket, or if I have a Whole Shebang - I don't get a reminder to go to the main event... right?  Otherwise, the logic could be really mushy.

**Comment by burlexpo** [comment]
> On Dec 7, 2017, at 9:20 AM, bethlakshmi <notifications@github.com> wrote:
> 
> Do you want this to be triggered manually (pretty easy) or automatically (doable, a bit more work).
> 
Automatically. I don’t want to have to remember to do it the night before. 

Logic looks fine. 
Yes, if a person only has shows on their schedule, they don’t get an email.
