### ISSUE TITLE
Need to be able to contact GBE participants based on participation type (Volunteer, Act, etc)

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#188]
I need to be able to email all performers with a certain status: i.e., "accepted for The Main Event" or "Wait-Listed for Sunday".

The two options I can see (and I'm open to other solutions) are

1) something (on the admin screen?) that quickly and easily let's me generate reports which include the performers name, status, and contact info.

or

2) some sort of mail form on the site that let's me email to subgroups of our users than can be selected based on certain attributes.  This might be more versatile (so we can use it to contact all volunteers, for example), but I suspect it's more complicated.

I am good with whichever solution is fastest for you guys.

**Comment by jonkiparsky** [comment]
I've created the basic code for this. Right now, there's a button on the show edit that allows us to grab contact info for Shows - volunteers or acts. The capacity exists to select waitlisted/accepted acts or to select volunteers by type, but I haven't done the UI work to make that happen yet.

**Comment by jonkiparsky** [comment]
Some modifications to this ticket: Rather than filtering on the site, add filtering information to the csv and let the user sort for what they want. 

Data types we want - fields to include   | optional fields (add if easy)
 * Acts - acceptance status/show/email | performer profile display name
 * Volunteers - role / email / parent event | profile display name
 * Vendors - email / display name / business name?  (haven't discussed this, but this seems right)
 * Teachers - email / class name | performer name / profile display name / 
 * Panelists - email / panel name | performer name / profiler display name
 * Moderators - email / panel name | performer name / profiler display name

@burlexpo this looks like a reasonable approach to this. If there are any fields you want added, either as required or optional, feel free to edit this comment.

**Comment by burlexpo** [comment]
Updated --

- Changed 'Acts' to 'Performers' to better match other lists
- Added "phone" to Performers, Teachers, and Volunteers, since they are the people we are most likely to need to call and say "Where the hell are you?"

**Comment by jonkiparsky** [comment]
Thanks, noted.

**Comment by jonkiparsky** [comment]
Act and Volunteer are fixed. Have to fix up Panelist and Moderator scheduling before I can finish those here.
