### ISSUE TITLE
Act status should be per allocation, not per Act

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#222]
Currently, we can't have an act waitlisted for one event and accepted for another. This is not an issue currently, but it's a flaw in the data model. 

To fix: decorate an act allocation with an acceptance_status flag, deprecate gbe.models.Act.acceptance field  (post 2015 event)

**Comment by bethlakshmi** [comment]
Technically speaking "accepted" is part of Biddable, Act inherits it from there, a bid is either accepted or not... so deprecation here is a pretty huge change that affects ALL bids.  

Instead of deprecating, if we ever want to get into casting acts into many shows, I recommend that we use Accepted only for "is the bid good enough" and then make something new if we want the act to be on waitlist for one show and actually cast into another show.

But... hugely low to me, because spending any effort on making it possible to cast 1 act many times runs counter to a whole of work that @burlexpo  has done to make it possible to create ever more places to cast ever more acts, making more places to cast fewer acts makes the expo less money. :)
