### ISSUE TITLE
Can't put a "Troupe" into a "Group"

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#226]
My brilliant plan of limiting who can see the tech sign-up forms for which shows may be foiled by the fact that while I can any user to  Group (using the Admin function), I cannot do the same for Troupes...

Any easy solutions?

**Comment by jonkiparsky** [comment]
We'd be using the Performer's contact profile in either case (Persona or
Troupe)
I might be able to add these automagically, though, so hold off on this.

**Comment by bethlakshmi** [comment]
Agreed - we  want the "contact" for the Performer for the Act inside the Show.

Not the actual people... because if we have, say, everyone in the troupe able to make updates we have stupid people problems.  Every member of the troupe is scheduled for the show, but only the contact person should be responsible for act tech info, bidding and communication with the Expo.

**Comment by jonkiparsky** [comment]
Closing this.
