### ISSUE TITLE
Auto resizing of uploaded images

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#231]
Post-February: When an image is uploaded, we should automatically generate a mini version - scaling to fit into a bounded box of some reasonable size, for example 200x300 px - in a separate directory. Code that deals with images should show the smallified version if the context does not call for a full-sized image. (ie, in a bio grid)

**Comment by jonkiparsky** [comment]
For reference, we can use the imagemagick library through the Wand bindings. import wand to get at the bindings, following is sample code for batch smallifying:

    >>> for f in files:
    ...     with Image (filename=f) as img:
    ...             img.transform(resize='200x300>')
    ...             img.save(filename=f)
    ...  
    >>> 

Docs at http://docs.wand-py.org/en/0.3.9/

**Comment by jonkiparsky** [comment]
@BenignCremator has created a cron job which checks the uploads directory for new files and minifies them to the correct scale. So this is now working, though we'd both like to have it running as part of the actual django app.

**Comment by BenignCremator** [comment]
Have written a script that scan the uploads directory for new files**, and makes mini version of any it finds.  Have set the script to be executed by cron every 5 min.  Tested it, and the test image popped into the mini_dir within 5 min.  So, works.  However, there are a couple of outstanding tasks on this.  We should move the script execution out of cron and into the upload process, so that it happens immediately when the image is uploaded.  Also, we should alter the upload directory structure for that there is a 'new image' directory, and after creating the thumbnail, it moves the image to a working image dir.  Also, we should move the mini dir to be parallel to the image dir, not stacked within it.

** It compares the upload dir with the mini dir, and looks for any file in uploads that does not occur in the mini dir.  Brutal, but effective.  Effective for dirs with less then a few thousand images.
