### ISSUE TITLE
PENDING RESEARCH Ticket items should update automatically

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#238]
*\* For NEXT year **
When I create a ticket on Brown Paper Tickets, I can easily set up price escalation by date (i.e., from 10/1 to 10/31 the price for this ticket is $30; from 11/1 to 11/30 the price for this ticket is $40; after 12.1 the price for this ticket is $50).

Our site doesn't pull this information automatically, so the prices on our site reflect whatever they were when the ticket item was created -- and then people get pissed off when they go from our site to BPT and the price jumps $50.

**Comment by bethlakshmi** [comment]
Right now, it has to be manual - I can see all the price points as separate ticket items - but we have "active" or "inactive".  For the moment, you can stop the screaming with manual updates...

To fix this long term, we probably need a way to sync the automatic change over date that you put into BPT - we'd want to check and see if it comes through on the API, because if it doesn't, we should talk to BPT about putting it in there.

**Comment by bethlakshmi** [comment]
Design structure:
- BPT is always the source of truth - we obey whatever it tells us about ticket availability dates - when we sync with them, and get conflicts BPT always wins, destroying GBE local data.
- We don't ever plan to update this on GBE
- not manual - GBE does not require a user to make the update visible.
