### ISSUE TITLE
3 Calendars only

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#257]
We have only 3 calendar views
1 - Shows & all GenericEvents EXCEPT volunteer opportunities
2 - all Classes
and
3 - All GenericEvent volunteer opportunities

For this ticket: get 1 and 2

Having 4 areas for panels, workshops, lectures, movement classes makes for 4 calendars that are hard to review and hard work with as class coordinator.

**Comment by bethlakshmi** [comment]
for reference, way back in October, I made code called 'calendar_type' - which should answer correctly for the 3 eventitem subclasses.  That could also be the submenu hook.

**Comment by BenignCremator** [comment]
More or less done.  In order:
1:  Added query for special events in case of shows.  This is 'special use' code, and not usable by non-GBE events.  Will need to update this come summer of 2015, but works for now.  Did this by feeding in 'Show' and 'Special Event' to the query, and concatenating the results.
2:  Have pulled the special class types and added back in the generic class query.  Since this was already in the code as an option, I only changed the options fed into the query function.
3:  Added 5 lines of new code to query GenericEvents and filter on 'Volunteer Opportunity'.  Works.  Well, in fact.  And serves as a template for other GenericEvents type, so, in summer of 2015, we can pass in other types of GenericEvent and have the code filter appropriately without hard coded queries.

Spent some time testing each of these, and no errors.  However, that said, there are an typo that I wasted two days on.  Hard to see a space where you expect a space, but a space should not be.  Life is trouble shooting and bug fixing.
