### ISSUE TITLE
Styling: highlight Act Tech alert 

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#263]
Yellow background to make it stand out

**Comment by burlexpo** [comment]
This fell out of the latest push. Reopening.

**Comment by jonkiparsky** [comment]
I saw this working on the live site last night, and I'm still seeing alerts highlighted with the same yellow. Can you give more details of where you see it failing?

**Comment by burlexpo** [comment]
It was failing on my home page -- but since I've submitted my tech info I don't see the alert (or the error) any more. 

@BethLakshmi told me about a 'see their home page' function she added. I'm going to see if that can shed any light. 

The Great Burlesque Exposition #9
February 20-22, 2015
www.Burlesque-Expo.com
#BurlExpo9

**Comment by jonkiparsky** [comment]
What function is that? Please share, I'm kind of working blind on the live site.

**Comment by burlexpo** [comment]
http://gbeadmin.webfactional.com/profile/manage

and then "View Landing Page" in the right-hand column.  It let's you see someone's personal pane as though you were them.

**Comment by burlexpo** [comment]
So, if I take a look at http://gbeadmin.webfactional.com/profile/landing_page/475 (Deanna Deadly's personal pane) I see the alert, but it's not highlighted.

**Comment by jonkiparsky** [comment]
It's highlighted for me. Maybe you need to clear your cache?

**Comment by burlexpo** [comment]
Clearing cache didn't do it, but logging out and logging back in again did.  Closing.
