### ISSUE TITLE
Cues needed on Act Tech info

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#267]
3 cue options
1st cue is ...
- required 
- has specific drop down (coming via email) for what causes the cue
- 5 settings - follow, backlight, center spot, cyc, wash
- each setting has a dropdown - Scratch will give default option

 additional 2 cues
- optional
- instead of triggered by pulldown, it has a text box
- same 5 settings for what happen on cue
- same 5 drop boxes

@burlexpo  will send me his notes with details on the pulldowns, defaults and a sample case.

**Comment by bethlakshmi** [comment]
Remove stage color & second stage color - replace with wash

**Comment by bethlakshmi** [comment]
follow spot on/off becomes follow spot color (one option is OFF)

**Comment by bethlakshmi** [comment]
add center spot

**Comment by burlexpo** [comment]
Props (check boxes; performer can select multiple options):
- I have no props or set pieces
- I have props I will need set before my number
- I have props I will need a stage kitten to hand me during my number
- I will leave props on-stage that will need to be cleared

**Comment by bethlakshmi** [comment]
Prop stuff is not part of the list of 3 cues.  They are their own types of cues

**Comment by bethlakshmi** [comment]
Include the sample as an image on the page.

**Comment by burlexpo** [comment]
Vendor Hall Tech sample

![vendor hall tech sample](https://cloud.githubusercontent.com/assets/5369404/5870231/8b5db1dc-a296-11e4-84aa-f5e2680eccfa.jpg)

**Comment by bethlakshmi** [comment]
@burlexpo - I need input - in the word docs you sent me, the order of light color choices varies from field to field.  For exampe:

Cyc Light = pull down menu is: 
- blue
- green
- OFF
- pink
- purple
- red
- white
- yellow

Wash - Pulldown menu = 
- white
- blue
- green
- OFF
- pink
- purple
- red
- yellow


These are the same lists of choices, but in different orders.

Two questions:
1 - does the order matter? - if I don't hear from you, I will assume "Yes", and make sure that I have the two options using the two different orders (this isn't hard, it just adds annoyance to certain areas of the code)
2 - Are the defaults always the first choice on the list?  Alternately - there can be a "blank" option - which forces the user to deliberately choose "off".  Here's the tradeoff, IMO, usability wise:
     - if the defaults are valid choices - the user will be more likely to submit a complete form, but if the defaults aren't what they really want, the stage crew would have to adjust on the fly.
     - if the defaults are "blank" at start, and we throw an error, we *force* the user to choose deliberately, which will screw with the stage crew less, but be more annoying to our users.

left unattended, I'll choose to remove "blank" as an option an default to the first choice on the list.

Let me know you want something different.

**Comment by burlexpo** [comment]
Yes, order matters.  The first color on the list is the default.

I'd rather have a default color, than a blank option.

**Comment by jonkiparsky** [comment]
Just as a usability thing, if you have a default color which people are
likely to actually want, then don't use the confirm switch. Usability-wise,
you should only use the confirm switch if you default to some unlikely
value, like "no lighting". If you default to a likely value, and require a
confirm, then you're just being annoying. (it's a default, but - surprise!
- not really)

Note also that leaving a default value is basically the same thing as
setting a blank default, since the lighting crew has no way of knowing
whether this is a choice or a failure to choose. This means that if you
pick the most likely setting as a default, you end up getting the least
useful information out of this form. (since you've conflated the two most
populous groups, "most-likely setting" and "didn't bother to choose" into
one). This might be okay, but it should be a conscious decision.
