### ISSUE TITLE
Act Tech info varies by location

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#268]
Rhinestone Revue (Friday 8pm)
The Main Event (Saturday, 8pm)
The Sunday Showcase (Sunday, 8pm)
all happen in the same location ("The Main Theatre")

The Bordello (Friday, 10:30pm) takes place on the Vendor Hall stage

*Right now, we need a hook so that people in the "Late Friday" show do NOT get the alert to give us act tech info/rehearsal selection - because if they do, the form will be wrong.

**Comment by jonkiparsky** [comment]
What's different about the act tech for Bordello? It's probably *a lot* easier to just bang out those classes (BordelloLightingInfo, BordelloAudioInfo, etc) and swap them in to the Bordello acts than to fiddle with showing this alert on a lot of conditional logic. Especially considering that a) we're going to need these tech infos filled in in any case, and b) we already have the templates for creating them, so there's no new ground to break. 
One request: if the audioinfo can stay the same, that will make life easier. That'll save me copying track info over from one to the other when I swap out the info classes.

**Comment by burlexpo** [comment]
There are two locations -- The Main Theater (which is where The 
Rhinestone Revue, Main Event, and Sunday Showcase are) and The Vendor 
Hall Stage (which is where The Bordello is).  We can use the same form 
for all shows in the Main Theater (The Rhinestone Revue, Main Event, and 
Sunday Showcase), but the Vendor Hall Stage (and therefore, The 
Bordello) has fewer lighting options than the Main Stage.

Vendor Hall lighting options are:
- wash (list of colors or off)
- Follow spot (list of colors or off)

Main Stage lighting options are:
- wash (list of colors or off)
- Follow spot (list of colors or off)
- Cyc (list of colors or off)
- Backlight (on or off)
- Center spot (on or off)

Audio and staging options (dealing with props) can be the same 
regardless of location.

**Comment by bethlakshmi** [comment]
FYI gang,

I grabbed this ticket - I have a bunch of the cue related work in my queue,
and this fits in there.

I won't have a commit for a while, since it's going to have DB changes, and
I don't want to mess up others until I have working code, but this one, the
logic of Act Tech forms, and the cue sheet info should all end up in there.

**Comment by eclecticmagpie** [comment]
I'm not sure I'm doing this right, but there is an audio difference between
the two stages -- we usually have a larger board set up in the Main
Theater.  Generally, you're unlikely to accidentally schedule an act with
excessive sound requirements into the Bordello, but if there's an easy way
to limit number of inputs available so that we *catch* it if, for example,
a singing ,dancing, stripping trio needs three wireless mics, two floor
mics because they tap dance, and have a jazz quartet accompanying them
which needs 12 more mics because they have a full drum kit and the other 3
musicians all double...that would be nice.

Hmm.  I've thought of a related problem that deserves its own number.  I'll
drop you a separate line.

--Michael


Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu
