### ISSUE TITLE
Act tech form should display which show act is assigned to

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#270]
The name of the show should display in the "Act Summary" box above the tech info.

**Comment by bethlakshmi** [comment]
I found out that when act rehearsals are set up, the show is shown on the same line as rehearsal selection:

http://gbeadmin.webfactional.com/deploy_stack/demo/acttechinfo/edit/198

(login as scratch)
It seems redudant to add it twice.  Last night, it wasn't visible on my screen, because I hadn't set up any rehearsal slots... now that I have more test data, it shows up locally for me.

Can we close?
