### ISSUE TITLE
Document how to add act tech rehearsals

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#271]
I see that you can do it - it's done in demo... what is the process for setting this up in a different database?

I see the tech rehearsals, but how do I make another one?  And how do I affiliate it with the appropriate show?

Given that they show up in GenericEvents, I would think I could create a new generic event using this link:

http://gbeadmin.webfactional.com/deploy_stack/demo/create_event/GenericEvent

And then maybe do something during scheduling that lets me affiliate the tech info with the show... 

Or I'd add it as a "volunteer opportunity" for the show... but that's not working either?

Having whatever process you used (even if I have to go into the database to do it) - is a HIGH, since I'll want to do it locally for testing.

Having a way to do it if I'm Scratch and need a form for it, is probably Medium - doesn't block the next update, but if we overrun the slots we have, we need to make more...

**Comment by jonkiparsky** [comment]
Currently, I'm doing the setup in the shell. It's generally a one-off process, so automating it is not high on my to-do list. (it's a lot easier for me to make a new rehearsal than to make and test a view to make a rehearsal)
The basic idea is, you create a generic event with the right parameters, then set up an event container connecting it to the show. 

The slightly more complex idea is that you get the shows, and loop over them to create the events all in one go. 

Looks like this:
    In [76]: for show in shows:
        for i in range (3):
            ge = conf.GenericEvent(title = '%s: Tech Rehearsal' %str(show), type = 'Rehearsal Slot', duration=3600) 
            ge.save()
            child = sched.Event(eventitem=ge, starttime = show.starttime- ((1 + i) * hour))
            child.save()
            ec = sched.EventContainer(parent_event = show, child_event=child)
            ec.save()
       ....:         

where shows is the list of show events, easiest to get them by 
    sched.Event.items.all()
    shows = list(_)
    # slice the list to select the ones you want, probably they're at shows[0:4]

and hour is a datetime.timedelta of one hour:

    from datetime import timedelta
    hour = timedelta(3600)

and as usual I've set up my models for easy reference:

    import gbe.models as conf
    import scheduler.models as sched

If I get the time I'll drop this stuff into gbeutils, but since I have a pile of things to get to, that's going to have to wait.

**Comment by jonkiparsky** [comment]
Documentation: done, see previous comment. 
Left to do on this ticket: 

 - script this process into gbeutils.py and test that
 - create a view to allow civilian admins to create rehearsals

**Comment by bethlakshmi** [comment]
Cool!

Thanks!

**Comment by jonkiparsky** [comment]
I notice that I left out location on this. 

Easiest way to do this is probably something like ge.set_location(show.location); ge.save() - this to be done after saving ge once. 
Thus is because location is not a parameter, it's an allocation, so it can't be set until the event is saved to the db, and has and I'd assigned to it.
