### ISSUE TITLE
Can't submit new act, tech info doesn't validate

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#285]
Not a burning issue, since nobody's allowed to submit acts at this point, but it's blocking testing of issues like #284

**Comment by jonkiparsky** [comment]
Had to comment out the cleaned_data functions (and remove dead columns from gbe_lightinginfo) to allow acts to submit. 
This is going to have to be fixed before we can push this.

**Comment by bethlakshmi** [comment]
Are you taking this or do you want me to?

**Comment by jonkiparsky** [comment]
Almost done

**Comment by bethlakshmi** [comment]
OK.  Thanks.

The fix will still give a nice error if someone submits an incomplete form, right?

**Comment by jonkiparsky** [comment]
That's the hard part - I had the rest of it an hour ago...

**Comment by bethlakshmi** [comment]
Yeah... it wasn't easy the first time, either.

My bet would have been to have two different forms  - one for Act Bid submit w/out cleaned_data checking

And one for act tech submit, with the cleaned_data...

**Comment by jonkiparsky** [comment]
1.7 has a method to add_errors to a form

1.6 sticks out its middle finger and says "screw you, buddy"

**Comment by jonkiparsky** [comment]
Okay, so that's one problem. ActTechInfoForm doesn't actually have anything
to do with ActTechInfo.
There's two hours gone for a bad name.

**Comment by bethlakshmi** [comment]
If you need to change data layout, please call me - I spent a fair amount of time trying to understand what Scratch wanted on CueInfo, and a fair amount of time building and testing logic that I really don't want to roll back.  It's not fantastically well documented in tickets, I've got word docs that he sent, and I've been listening to him rant about it for a few weeks.

If the problem is isolated to form data checking - I trust you and I think we spec'd out the error logic well enough to not have horrible surprises.

The original implementation came from the following logic on my part:

1 - I originally wanted to use the data model object's "is_complete" method to check if the object was complete.  As it turned out, django docs pointed me at the cleaned_data function for that reason - because the instance was supposedly available.  

2 - What found in trial and error was that the model instance was the OLD data, not the NEW data, so the form was obviously failing for intended reasons.

Reading this:

https://docs.djangoproject.com/en/1.6/topics/forms/modelforms/#django.forms.ModelForm

I may have been addressing the incoming data incorrectly, I may have actually wanted form.instance instead of what I was using (don't remember... it didn't work... I gave up...)

3 - Could have hooked in and overrode the logic elsewhere... but at that point I was down the road and had already navigated cleaned_data sufficiently to know it would give the error I wanted in the place I wanted it (in the section of the form that had the problem)

I stand by the idea that the error logic for a form belongs in the form itself.  We don't have any logic that transcends a single form - so it's contained well enough there, and we already have templates that look for form errors and display them... so it fits error handling.

I am likely to be headed to bed soon, but can be woken up if we need to discuss database organization.

**Comment by jonkiparsky** [comment]
The data layout is staying the same. The only db change I've made is to
remove the fields you took out of lightinginfo, so they don't break things,
and to add Mike's new field.

Anyway, if you find yourself struggling call me in sooner, not later. I've
cleaned up a lot, but it would have been nice to not have to do all of that
tonight.
I'm ready to go with a push at this point, or I can hold it for tomorrow if
you want to be awake for it.

**Comment by bethlakshmi** [comment]
let's go for it.

**Comment by bethlakshmi** [comment]
Do you want me to run the DB code?

**Comment by jonkiparsky** [comment]
Please do.

**Comment by bethlakshmi** [comment]
Running right now...

**Comment by bethlakshmi** [comment]
ok... can you update the code?

Everything but gbe_cueinfo is in there... and if you update the code, we
can update cueinfo by syncdb...

For some weird reason SQL through php my admin is giving me grief on
syntax, and debugging this doesn't seem worth it.

**Comment by jonkiparsky** [comment]
okay, pulling into git-drop now
