### ISSUE TITLE
Need .css/JavaScript wishlist

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#287]
also asking @jonkiparsky for input

I've found a .css/JavaScript guy.  I've pointed him at the two "halves" of the site and told him I'd like site No. 2 (gbeadmin) to look more like site No. 1 (www.burlesque-expo.com), but there were some definite places we were looking for css or JavaScript help.

I'd love you guys to help pull together a task list for Chris (the .css guy) ASAP.

Here are some of my thoughts:
- install some Google fonts so we can have headers and subheaders in more stylish fonts
- "pretty-fy" the popover boxes on the various shows (rounded corners, drop shadows)
- add some color to the site in general
- add a background image on most pages

**Comment by jonkiparsky** [comment]
First thing I'd suggest would be to work on making the calendars dynamic,
sort of like what I did last year.
From there, there's probably a lot of places where we can make better use
of resources by not going back to the db constantly.

**Comment by bethlakshmi** [comment]
Let's see....  on the level of new-person intro, I want to:
- cover that we use github and get him an account
- cover that we need him to use his own local test environment and to do testing for himself - that we have no unit tests or automated regressive tests of any kind.
- I need him to take ownership of his own multi-browser testing - we've been using very vanilla CSS/HTML and no JS at all.. if he adds complexity, I need him to own testing it.  Ground rules would be "major current browsers" - Chrome, Firefox, IE, Safari. I'm OK with living in the idea that all our users are using the common auto-updated browsers.
- we assign bugs and work in issues - ideally I'd like him to let the team know what he's doing by assigning himself issues, and he's welcome to hit us with back end bugs when he encounters them.  We generally leave items unassigned when in doubt, he should be prepared for us to throw him JS/CSS related bugs as we find them.
.... stay tuned, I'm chunking thoughts by comments...

**Comment by bethlakshmi** [comment]
For near term work - I think we want to stay to things that are reasonably benign.  I agree with @jonkiparsky  that helping with doing fewer database lookups would be nice, but I am afraid at significantly changing the server/client flow this late in the game.

Instead... I'd focus on:

- the horror of the hover on the show display - I'm open to virtually anything better - team preference was clickable with an icon, and I'd be totally OK with a redesign that lets the info show up somewhere on the page when clicked instead of popping on top of the current page... but if he's got UI design skills, I'm willing to listen.

- JS pull down menus instead of hover (we have an open old ticket)

- Jquery or similar on ALL tables - to make every reasonable header cell sortable. - we have a few different templates for tables that would need to be updated.  First target would be scheduling tables, because we will still be using them quite heavily.  Next would be the tables for User Admin.

- Design proposals and then implementation per agreed upon ideas of layout and beautification of the landing page, the calendar,  the event description page, the event list pages,  then the various bid forms, and the view bid page, in that order.  My ordering is somewhat geared towards my guess on frequency of use.

After that list, I'd have him get into the staff areas... but that's likely to be enough to keep him busy for a bit...

**Comment by bethlakshmi** [comment]
After 2015 GBE happens, I would agree that we could do even more interactive work, and I'm not sure what Jon's thoughts on reducing DB interaction are... but thoughts I have include:

- a sexy user lookup tool for scheduling - Scratch once said he'd like user choosing for teachers/panelists/volunteers to be "like Facebook" with a nice lookup tool.

**Comment by jonkiparsky** [comment]
Yes. Fix the menus. I'll buy the guy a beer if he fixes the menus.

**Comment by bethlakshmi** [comment]
Another one, that may be personal - having a way of structuring the landing page so that areas of focus can be automatically open or "rolled up" into a real estate saving panel.  In particular, we care a lot about bids and what's proposed/a draft/accepted when we are organizing proposals... so that would be open and highlighted early on.  Then (like now) we care about tickets, schedules, and act tech forms - we don't want bids to go away, but I'd happily see that panel on bid management reduce to something small that could be opened with a + sign or something to see the older info.

**Comment by burlexpo** [comment]
So -- my priority is make the 'internal' site not hideous.

I understand there are a ton of usability, workflow, optimization, etc. 
things that Chris could do, but he is a very limited resource.

I will ask him about getting set up on GitHub and then I would like him 
to (in this order, I think)

- fix the menus
- fix the hover (I don't think the hover functionality is so bad, just ugly)
- make the site prettier (my ticket items)
- Jquery tables

I don't think we'll get all of this out of him, but it's a start.

**Comment by bethlakshmi** [comment]
Also... a way to set a "more..." link for long text fields.  Most useful on event lists, but I think we also talked about it with vendors.

**Comment by burlexpo** [comment]
I thought about this one, but I think it really only effects a handful 
of people (those of us with mega-staff powers).  As we move forward 
(hopefully), any single person will have fewer types of bid to review, 
so the real estate issue will be less pressing.  This is a post-2015 fix.

On 1/26/15 11:36 PM, bethlakshmi wrote:
>
> Another one, that may be personal - having a way of structuring the 
> landing page so that areas of focus can be automatically open or 
> "rolled up" into a real estate saving panel. In particular, we care a 
> lot about bids and what's proposed/a draft/accepted when we are 
> organizing proposals... so that would be open and highlighted early 
> on. Then (like now) we care about tickets, schedules, and act tech 
> forms - we don't want bids to go away, but I'd happily see that panel 
> on bid management reduce to something small that could be opened with 
> a + sign or something to see the older info.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/287#issuecomment-71588606>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com

**Comment by jonkiparsky** [comment]
these mixed fonts here: http://gbeadmin.webfactional.com/deploy_stack/betty/scheduler/view_list/Special
make me cry bitter tears.

**Comment by bethlakshmi** [comment]
Just pushed a very, very small fix to at least reduce the volume of Jon's
tears.

**Comment by burlexpo** [comment]
While I don't like the mix of *those* *particular* fonts (I haven't looked at the fix yet), I think that 3 fonts (header, subhead, and body) on a page are fine.

**Comment by jonkiparsky** [comment]
Goldurn it, where's that +1 button?

**Comment by jonkiparsky** [comment]
@burlexpo Mixing fonts can work, sure - but unless you're a good designer, it's more likely to fail than to succeed. Since we don't have any good designers on the team as yet, we should be conservative and follow sensible rules in design.

**Comment by burlexpo** [comment]
Ah. I am a *good* designer -- I just don't use .css enough to do what I 
want to do for this site, but my graphic design skills are up to the task.

On 1/27/15 11:05 AM, Jon Kiparsky wrote:
>
> @burlexpo <https://github.com/burlexpo> Mixing fonts can work, sure - 
> but unless you're a good designer, it's more likely to fail than to 
> succeed. Since we don't have any good designers on the team as yet, we 
> should be conservative and follow sensible rules in design.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/287#issuecomment-71673398>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2015
Feb. 20-22, 2015
Cambridge, MA
www.Burlesque-Expo.com

**Comment by jonkiparsky** [comment]
Add to the wishlist: #172 

Actually, I really need to know more about the guy's skillset before I know how to use him. Betty and I can certainly figure out fixes for all of these things if we need to, it seems to me that it makes a lot more sense to figure out what this guy's strengths are and play to those, instead of just throwing issues at him.

**Comment by burlexpo** [comment]
Chris' skill set is at http://chrismedinaphp.com/

I gave him the pre-game requirements and he said:

*"Oh, nice you're using version control and it seems to be a python application.

I'll checkout the repo and setup a local testing environment. Based on my discovery I'll have a better idea of what will be involved to update look and feel.

Once that's done I can send over a proposal to kick off the design fixes for your site, which will itemize cost, completion time. If 7 business days works for you that would give enough time for testing, committing...

Will update you this afternoon on my discovery. Thanks."*

Which seemed like a pretty good response...

**Comment by jonkiparsky** [comment]
Adding more, there are various walls of text around the site (for example, act bid and vendor bid, or on act tech edit) that are really impossible to read - they're like the black spaceship parked at Milliways, your eyes just slide right off them. I'm sure all of that information needs to be presented, but perhaps Chris would be able to help us present it in a way that would be more effective.

**Comment by BenignCremator** [comment]
On 01/26/2015 09:05 PM, Scratch wrote:

> I've found a .css/JavaScript guy.
...
> I'd love you guys to help pull together a task list for Chris (the .css
> guy) ASAP.

So, currently, the calendar is requesting the css_class property from 
all scheduled events.  Unfortunately, this is the only place in the code 
where this property occurs, so it is returning 'None'.  We should have 
the model? populate it with something useful.  My original idea was 
something like:

event.event_type_name+'.'+event.confitem.sched_payload['details']['type']

so it would end up looking like:

Class.Movement
GenericEvent.Special Event
etc...

Then we could do different style things for both levels of event. 
However, that was my first thoughts on the matter.  From here on out, 
this is a matter of what HonestCoders thinks is useful and what 
jonkiparsky thinks we can include.

Hunter

**Comment by HonestCoders** [comment]
Hey all,

Just wanted to say hello and that I am reading comments. Nice to meet you all

As for the architecture for implementing multiple style classes for elements in same view(assuming MVC/MVP) I'll let you guys decide on that if that's how you would like to approach it. More of a PHP guy than a Python man myself so I would be working with template, .js(if needed), .css files mainly.

I have no qualms about any of the features you've gone over so far in this thread.

**Comment by bethlakshmi** [comment]
some of this is closed by django cms - and I assert that the remainder would do better as a new ticket if it is still valuable
