### ISSUE TITLE
2015: Add Django share to events

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#298]
Add https://github.com/docc/django-share to classes, panels, workshops, master classes, shows, and special events so people can share those pages on Facebook, Twitter, etc.

**Comment by bethlakshmi** [comment]
The "share this page on Facebook" is now available in the django-cms from GBE-412.
However - we should design the place we'd want this to show up the Event pages if we want to use this there.  The challenge will be the elegant fusion of django-cms and GBE code.  The way Django-cms works, I can inject a "static placeholder" on the page.  The static place holder is static, because it shows up any time that template is used - for reference, the header and footer... which is a win, we like that consistency.  but do we want every page to have the share link?  and were do we want it on the page?

**Comment by burlexpo** [comment]
We figured this out.  Go us.
