### ISSUE TITLE
Reporting - tech info?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#307]
Sorry if this was covered somewhere, but is there an easy way for me to see who has submitted their tech info and who hasn't? I poked around with what's available to me on http://gbeadmin.webfactional.com/scheduler/list and can't find anything.

I seem to remember a screen on which I could place acts in an order... but I can't find it on the live site.

**Comment by bethlakshmi** [comment]
I started the bare bones of ticket #261 - which is hidden away in the current code base, because when i say bare bones, I mean "not at all functional".   

That is *different* from what Jon did to do act ordering, which is here:

http://gbeadmin.webfactional.com/scheduler/acts

But has problems ... @jonkiparsky and @BenignCremator - I feel like Jon fixed this problem once before... are having code check in clobbering here?

**Comment by bethlakshmi** [comment]
For the record it's working in demo stack:

http://gbeadmin.webfactional.com/deploy_stack/demo/scheduler/acts

**Comment by bethlakshmi** [comment]
http://gbeadmin.webfactional.com/acttechinfo/view/138

(Need to have "Tech Crew")

**Comment by bethlakshmi** [comment]
Closed with https://github.com/bethlakshmi/GBE2/commit/5e8f42f164915d9a601a4fac9b9c9e06189b0a98
