### ISSUE TITLE
Allocation of volunteer shifts

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#314]
I know that there are "Staff Area" volunteer opportunities and volunteer opportunities which are attached to shows.  During (for example) The Rhinestone Revue, we'll have a couple of security people/ushers. Some will show be stationed in the theater, some in other places.  

My question is, if I create some security shifts using the tool on http://gbeadmin.webfactional.com/scheduler/edit/Show/15 and I select the **Volunteer Type** "Security/usher" from the pulldown menu, will those volunteers show up when the Security Chief looks at the resports of "All security people"?

Please let me know ASAP, as it affects how I create and assign volunteers.

**Comment by bethlakshmi** [comment]
We haven't done reports yet, but what I thought we talked about last week was that the chain for a staff area was based on the parent event, not the volunteer opportunity - ie, the Staff Area thing.

We didn't cover this.  As far as I know, there'd be design work to doing it this way (booking a volunteer for a show and expecting them to be part of security).  And we'd want to spec all the cases for what shows were, since we're now adding complexity.

But leaving open for Jon to give more info, this area of the data has been his zone far more than mine.

**Comment by burlexpo** [comment]
Just to be clear, I am just asking for clarification.  I can deal with whatever the current reality of the site is.  I am **not** (at this time) asking for an enhancement (although I may at some future point).

**Comment by jonkiparsky** [comment]
I think Betty's right that the staff area approach is what we had in mind when we were talking, and I think it's the right way to go - even though I can see how you'd like to set up the security slots dependent on the shows. 
It shouldn't be a problem to get a list of opportunities of type "Security/usher", or of the people assigned to them, however. So if you wanted to have security for shows depend on the shows, we could make that work. And since opportunities don't have to have the same time or duration as their parents, you could schedule pre- and post-show security shifts (for setup and strike, if needed) and those could be associated with the event. 
If it's more convenient to tie these shifts to shows, I **think** this should be workable, if we determine ahead of time that the staff area report for security depends on the opportunity type. You can then create a "Security" staff area to carry any security shifts that are not tied to particular shows, but what we're reporting from is the opportunity type, not the staff area. I hope that makes sense. 
@bethlakshmi - does this seem correct to you? It does raise some complications for reporting, I realize,  but I think they're manageable - what do you think?

**Comment by bethlakshmi** [comment]
All things are possible... with time... I admit I'm nervous about adding even a tiny bit of complexity at this point as we are under the gun...

Scratch - how bad do you want it?  If "not much" let's defer that to post-expo.

Long term... I'm cool with it... but the back of my head wants to back up and think about the connections of:

- what a volunteer bids
- what opportunities go where in scheduling
- what the most useful connection is.
