### ISSUE TITLE
Build/Strike Screw-up

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#352]
I think I've made a mistake in setting things up, and I need your help.

I noticed that if I go to http://gbeadmin.webfactional.com/reports/staff_area/221 it only displays "Set-up" so I think I've configured something wrong, since I know I have about 10 peopleset-up for Strike.

I'm not sure what I've done wrong, but if you can take a look at the volunteer shifts, etc. and let me know what I need to do to fix it, I will.

**Comment by jonkiparsky** [comment]
Looking in the admin, I do not see a GenericEvent titled anything like "Theater Strike". Can you give the exact name of the event that you've assigned these people to?

**Comment by bethlakshmi** [comment]
Scratch and I dug in, these were setup very weirdly.  Scratch is cleaning
up with research data I just sent him.

We definitely have enough power here to shoot ourselves in the head with
scheduling.  Next year I think we want to refine inputs and force some
business logic in here.  Things like:
- What happens when you add a schedule item for a Volunteer Opportunity
from the event list page?  Should that be allowed?  It won't chain to a
parent staff area.
- Should you be able to allocate volunteers directly to a Staff Area?

**Comment by jonkiparsky** [comment]
What was the nature of the data screwup?

**Comment by burlexpo** [comment]
It was PEBKAC.  Instead of creating a Staff Area with multiple attached volunteer shifts, I created two different Staff Areas with the same name.

**Comment by bethlakshmi** [comment]
Also, I found that the "Theater/Build" volunteer opportunity had a second
session added.  That session wasn't part of "Build/Strike" because it was
made with "add session" on the event review page.  When a second session is
added there, the second session does have the same parent container as the
first session.
--- I manually fixed this.

AND, the staff areas had max_volunteers set for them.  Which makes it
possible (and enticing) to allocate them in volunteer review pages,
particularly since there's nothing on the volunteer review pages that
suggest what type of event you are working with (Staff Area vs. Volunteer
Opportunity).  That meant that we had a "Build/Strike" event for Thursday
at 6:00 PM and a "Theater Build" event for Thursday at 6:00 PM and
volunteers were booked both places.

I fixed that too - I removed the "max volunteers" on staff areas, so that
Scratch wouldn't be tempted by them.


-Betty
