### ISSUE TITLE
Mimic burlesque-expo front page styling in django-cms

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#412]
In order to get the static site and the live site to play nicely together, merge styling/content from static site into dynamic site. This will be the new front page, and should be editable by scratch.

**Comment by bethlakshmi** [comment]
After some digging, I found:

- https://github.com/WnP/djangocms-css-background - prototype is on GBE-412-alt branch.  I'm not loving it - see long rant in comments.
    - as a side note, though - https://github.com/WnP/djangocms-placeholder-attr - is interesting and worth remembering for coding use later, perhaps.

- https://github.com/divio/djangocms-style - my thought for a next thing to try - may not fix all our issues, but may be a good fusion between developers and @burlexpo  as we have to do some setting configuration, but once done it lets Scratch play with our styles w/out bugging us. :)

- http://www.djangocmsthemes.com/ - I keep wandering by this one - it provides only 5 themes, but when I dig into the theme gzip packages, they are a nice layout of CSS and templates.  If we could get these to work w/ our site, we could give @burlexpo  the ability to upload whole style sheets AND js AND layout things.  I somehow fear the glossy slickness, though, can't say why...

Because these are somewhat overlapping, I fear throwing them all on there, for fear of causing undebuggable chaos, but I'm willing to give the chaos a shot if others are willing to join me in the potential insanity.

**Comment by bethlakshmi** [comment]
Notes - I just tried to integrated djangocmsthemes on a local branch.  It was such a complete failure I won't bother to checkin.  Apparently it doesn't work with django-cms 3.0 and/or is hasn't had any updates to the codebase in 2 years, so I pronounce that package dead.

**Comment by jonkiparsky** [comment]
Yeah, I'm thinking of failing back to just doing the styling in hard-coded
CSS and letting scratch content himself with editing text for now.
At least, I can get that working...

**Comment by bethlakshmi** [comment]
styling is done... to do:
- sync with Master
- test Jon's recent updates
- update requirements.txt
- pull request
- push to site

**Comment by jonkiparsky** [comment]
Betty's work on GBE-412-alt does not actually complete this ticket, but it provides the path to do so. Closing.
