### ISSUE TITLE
Resize function doesn't work in Gallery Admin

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#461]
It'd be easier for me to show you live, since I can't track down a URL to demonstrate what I mean.

There's a clearly labeled 'resize' function as part of the Gallery.  When I try to use it I get a 500 error.

This can wait until after August 1.

**Comment by bethlakshmi** [comment]
Is this the place you mean?
![screen shot 2016-01-10 at 9 33 54 am](https://cloud.githubusercontent.com/assets/4542707/12222028/4b05eeea-b77d-11e5-989b-28c4d2414bf0.png)

**Comment by bethlakshmi** [comment]
OK, the window I'm pointing to here is actually having an impact on how images work... It's not exactly doing what I would expect, but I'm not sure that this is the area that @burlexpo actually means, since the "Gallery" is somewhere else in the system, and I can't find any sort of resize that applies there.

**Comment by burlexpo** [comment]
Something got fixed, which is good, but I think what I actually mean is "Slider".  Go to http://burlesque-expo.com/roll-winners/?edit&language=en-us and look at the first slider gallery.  There's no option to scale the images, either manually or automatically, so they display poorly.

**Comment by bethlakshmi** [comment]
Right.  So the problem is that the slider, itself, is scalable.  But the images can't be edited, particularly, so a wide slider with a narrow image is bad looking (or vice versa).

What would you want it to do?  The way the CMS stuff works is:
- there's filer - which controls the images in the files.  
- there's thumbnails that are separately stored files for those images (also managed by the filer)
- there's images - which do the business logic of single image at a time display
- there's the gallery - which does the list of images all collected into a page
- there's the slider - which does the slider

In the way the system thinks of things, images, gallery and slider are all peers, they all reside on top of filer.  So I can't smoosh the controls of images into the slider... but I could potentially get the slider working with thumbnails, and then you could have the way to make a bunch of thumbnails that are all a good looking same-size image.  But it may mean that to set up a nice looking slider, you have to go bouncing around the system a lot.
