### ISSUE TITLE
Bid review pages show complete list of options instead of selected options only

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#491]
See screenshot:

![optionlist_bug](https://cloud.githubusercontent.com/assets/5283553/9156754/0939edba-3eb3-11e5-82b1-c9eb83fbbc32.jpg)

@bethlakshmi @burlexpo - can one of you confirm that this is actually a bug? I don't want to go fixing incorrect behavior that you actually want for some reason.

**Comment by burlexpo** [comment]
This is *not* a bug.  It's a stopgap fix.  At the top of the form it says

In lists of choices:

  * /Italic choices/- were not selected
  * *Bold choices*- have been selected

which is the behavior that is being exhibited.  Betty is going to fix 
this display issue later, but for the time being, it's manageable.

**Comment by jonkiparsky** [comment]
Weird. Well, might as well ticket it then. I assume the correct behavior would be to show the selected items and not the unselected ones - right?

**Comment by burlexpo** [comment]
I don't recall what the correct behavior is.  I do not believe it is as 
you describe (show the selected items and not the unselected ones) 
because there are cases where the reviewer wants all of that 
information.  @BethLakshmi is aware of this.  I don't think it needs to 
be ticketed, but feel free if you like.

**Comment by bethlakshmi** [comment]
repeat the work we did in Volunteers for:
- classes,
- proposals
- acts
