### ISSUE TITLE
Nancy Barrett: "Problems with web site"

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#540]
Received this email, I think all of you did as well. Has anyone addressed this? I'll communicate with her if I don't hear a "yes" by EOD. 
If you did work on this, please use this ticket to track the issue - what was wrong, what work was done to fix the problem, what is the current status of the issue etc. 

> Hi,
> I was having problems getting into site via selecting "I Want to..." Sell my stuff. Was able to get in to  (hopefully) apply to vend via  my profile. Already paid vending fee and bought whole shebang tix!

**Comment by jonkiparsky** [comment]
@burlexpo @bethlakshmi - has this been dealt with? It sounded like both of you thought it was covered, but I see no followup here.

**Comment by burlexpo** [comment]
It's been dealt with in the sense that the vendor is now entered into 
the system and has paid for her booth.

I'm not sure it's been dealt with in the sense that someone sat down 
with the vendor to figure out what the problem was and to determine if 
it was a one-time thing or a persistent issue.

On 11/10/15 10:54 PM, Jon Kiparsky wrote:
>
> @burlexpo <https://github.com/burlexpo> @bethlakshmi 
> <https://github.com/bethlakshmi> - has this been dealt with? It 
> sounded like both of you thought it was covered, but I see no followup 
> here.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/540#issuecomment-155654537>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2016
Feb. 5-7, 2016
Cambridge, MA
www.Burlesque-Expo.com

**Comment by bethlakshmi** [comment]
Closed because most of her problems where with login.  It was a bug, we fixed it, she reported she was good.
