### ISSUE TITLE
Weird login issue

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#542]
I went to gbelive.webfactional.com

I logged in and was immediately taken to the "we're sorry" page instead of my personal homepage.

Thoughts?

**Comment by bethlakshmi** [comment]
Working on it.

The problem is that Scratch chained sub pages off of "Home" which is
supposed to be the source page of http://gbelive.webfactional.com

But if you make the home page into a menu root, things behave poorly.  I
never tested that and I can't make that work quickly.

I'm working on a fix but it will take a bit.  Hang on on the live site
please.

**Comment by jonkiparsky** [comment]
I'm home now. @bethlakshmi, let me know if you need another brain on this.

**Comment by bethlakshmi** [comment]
Thanks Jon!

Weirdly, I hosed quite a few pages in doing something theoretically
benign.  I will have to test more later and figure out what the hell I did,
but at the moment I am in aggressive manual recovery for the 4 pages I
broke.

The upshot is, that my painful fix seems to also fix this issue... but what
went wrong the first place bears investigating.

**Comment by jonkiparsky** [comment]
@bethlakshmi - reassigning to you since you seem to have run with this one. Thanks for doing that.

**Comment by jonkiparsky** [comment]
@burlexpo @bethlakshmi - is this issue resolved, or is there more work to do here?

**Comment by burlexpo** [comment]
Yes, fixed,
