### ISSUE TITLE
Vanishing/reappearing edit bug

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#552]
Again.

I haven't touched it.  I went to browse the page and there's no data there -- just a menu item.

I am *extremely* nervous about stuff randomly disappearing in general, more so when we don't yet have a back-up scheme in place. (Do we?)

**Comment by burlexpo** [comment]
And it has vanished from the test site too.

**Comment by BenignCremator** [comment]
On 11/11/2015 09:05 AM, Scratch wrote:

> "Roll of Winners" page has vanished

That is not good.  Is the 'Roll of Winners' hosted as a static page or 
off-site page?  It seems to be back now, did someone fix it, or is there 
something happening intermittently?

> I am /extremely/ nervous about stuff randomly disappearing in general,
> more so when we don't yet have a back-up scheme in place. (Do we?)

Backups are occurring to my personal server.  They seem to be running 
ok, but I am still in the process of monitoring their progress. 
However, what we do not have is a full recovery plan in case we need to 
use the backups.  Also, I added audio to the backup scripts, as I had 
missed that the first time around.

Hunter

**Comment by jonkiparsky** [comment]
I am also seeing the page on the site at present (the cropping on Kiki Allure's shot needs attention, but the page is there). I haven't been anywhere near the live site in quite a while, all of my work has been at the repo end. @bethlakshmi, have you been on the server? If not, this is a little bit mysterious. 

@burlexpo  - can you give more detail about what "vanished" means? Was the menu item present? If so, what happened when you went to it? If not, did you try going directly to the url, and what did you get when you did?

**Comment by burlexpo** [comment]
Ok -- more details.  What seems to have "vanished" is my ability to edit said page (which I'm not sure I ever had).  What happens is, when I'm *not* logged in, I can see the page.  When I *am* logged in (and therefore in edit mode on the CMS, since there doesn't seem to be a way for me to be logged into the site but not logged into the CMS), the menu link is there, but the page has no content (to me).

Does this help?

**Comment by jonkiparsky** [comment]
Very much so. I'm looking at the page now, and when I'm signed in, I can see content on the page, but when I select "edit", the content goes away. I don't know if this is exactly what you're saying, but it seems like it's pretty close. 

I'm pretty sure this is a CMS configuration issue. @bethlakshmi has a lot more experience in this area than I do, so I'm hoping she'll chime in on it, but I can try to understand it on my local copy if that'll be useful.

**Comment by burlexpo** [comment]
I talked to her about this over dinner.  I think she's going to step up 
and grab it.  If I'm wrong, I'm sure we'll find out on the conference 
call tomorrow ;-)



On 11/11/15 10:01 PM, Jon Kiparsky wrote:
>
> Very much so. I'm looking at the page now, and when I'm signed in, I 
> can see content on the page, but when I select "edit", the content 
> goes away. I don't know if this is exactly what you're saying, but it 
> seems like it's pretty close.
>
> I'm pretty sure this is a CMS configuration issue. @bethlakshmi 
> <https://github.com/bethlakshmi> has a lot more experience in this 
> area than I do, so I'm hoping she'll chime in on it, but I can try to 
> understand it on my local copy if that'll be useful.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bethlakshmi/GBE2/issues/552#issuecomment-155983487>.
>


-- 

------------------------------------------------------------------------
The Great Burlesque Exposition of 2016
Feb. 5-7, 2016
Cambridge, MA
www.Burlesque-Expo.com

**Comment by bethlakshmi** [comment]
I can see the page whether edit is on or not.

**Comment by bethlakshmi** [comment]
Confirmed that Scratch's account can NOT see the page when in edit mode.
In fact he can't see ANY page!  So... it's consistent.?

**Comment by jonkiparsky** [comment]
Huh. Looks like I've got the django-hijack stuff pretty much ready, in case
you want to see the world from Scratch's perspective. :)

**Comment by bethlakshmi** [comment]
OK.  It's late and I have no new ideas.
Scratch - I'm sending you my password, which will work for editing pages until I can find a fix.
- new user didn't work - had same problem as Scratch 
- all pages EXCEPT the home page don't work on either account - I don't know why home page is special.  That INCLUDES a page Scratch made (Vendor Information) - which is even harder to explain.
- same behavior is happening on test site


I'll play on test, not on live and try to figure out what the hell is going on.

**Comment by bethlakshmi** [comment]
https://github.com/divio/django-cms/issues/4692

**Comment by bethlakshmi** [comment]
Also - gbelive has the capability to actually see and edit.
gbelive is the very first user, so there's something special about that...

**Comment by burlexpo** [comment]
New instance -- same problem, different page.

I login to www.Burlesque-Expo.com, all is fine.
Whether or not I'm logged in, if I go to http://burlesque-expo.com/guests-2016/ all is still fine.
I click the 'edit' button and the content of the page vanishes (to me).
If I logout, the content of the page returns.

I can consistently reproduce this bug.

**Comment by bethlakshmi** [comment]
https://github.com/divio/django-cms/issues/4713

**Comment by bethlakshmi** [comment]
http://stackoverflow.com/questions/33818497/django-cms-edit-gives-no-data

**Comment by bethlakshmi** [comment]
It's happening on ALL pages, and on ALL users.  It's like it's spreading.

**Comment by BenignCremator** [comment]
On 11/19/2015 10:49 PM, bethlakshmi wrote:
> It's happening on ALL pages, and on ALL users. It's like it's spreading.

Take a look at what the URLs in the menus are, and if there is a 
hyperlink in the <a href>.  I was thinking that the problem might not be 
empty pages but links that connect to empty pages.

Hunter

**Comment by bethlakshmi** [comment]
The URLs seem fine.  By fine, I mean that they either:
 - are correctly linking to the appropriate tag
 - are referencing accurate page ids.

In fact the problem is consistent in two paths:
1 - select a publicly visible menu item, click edit to go into edit mode
2 - go to the page admin - select the page there, it automatically puts you in edit mode.

These two methods use two different URLs but produce the same result.

It appears that betty still has access to edit home, but nothing else.

**Comment by bethlakshmi** [comment]
Capturing notes for the night... I studied and studied and found that the vendor info (one of the many broken pages) had only "en" placeholders, but that I couldn't edit the en version of the page.  But, when I change all the placeholders for "en" to "en-us" I can now edit the page.

Hrm...  There's no non-excrutiating way to do this.  But I'm tempted to grab a back up of the db and try the same technique on live.  Not tonight.  Too late for more crazy.

**Comment by BenignCremator** [comment]
On 11/20/2015 01:02 AM, bethlakshmi wrote:

> Hrm... There's no non-excrutiating way to do this. But I'm tempted to
> grab a back up of the db and try the same technique on live. Not
> tonight. Too late for more crazy.

I feel for you.  I have removed every package in the entire PYTHONPATH 
that I installed yesterday and reinstalled based on the current 
requirements.txt file from GBE master.  I also dropped and reloaded the 
DB from a backup from 25th Oct.  No change to behaviour, test is still 
broken, still giving the "KeyError: u'__module__'" and the only thing a 
web search is uncovering is an issue with six that produces an nearly 
identical error traceback as ours, but the proposed fix involved 
upgrading to the version of six we are using, and referenced by version 
number in the requirements.txt, which appears to have been specified on 
Sept 19.  I believe that test has has been updated since then.  Removing 
and install version 1.5.2 or 1.10.0 do not help, so I do not think that 
the problem is six per se, but the error chain is going through that 
package.

Hunter

**Comment by bethlakshmi** [comment]
OK. I've found a workaround, now I'm taking it one step farther.

The problem seems to center around languages - we have 2 - en and en-us.  That came from me trying to do something in django-cms and not being able to do it w/out both in place.  (not sure that something is even valid anymore).

I went through the DB and found that in a number of places Django CMS has been mismarking parts w/in pages.  Pages that SHOULD be "en-us" are getting marked "en".  

The system has a failback mode - when users are viewing it NOT in edit mode, if the "en-us" version isn't there, it will fail back to an "en" version - so users see it fine.

But when editors view it, the system gets EXACTLY what data is available for "en-us" - which in most cases was nothing.  Why this was intermittent, I can't explain - although I do see references to cache keys, so my best theory is that the problem is somehow connected to caches that get changed or dumped.

Current workaround - I combed through the live DB (after much testing on local) and fixed all the bad refererences.  I also successfully KILLED every "en" page, so that entire system is using en-us.

That gives Scratch the ability to edit pages back.

I tried the next logical step - eliminate the secondary language (en) so that the user is always working in "en-us" - this is failing and I can't explain why - the editor can edit, but the user can't see the pages.

Rather than screw up live, I'll go back to local and continue to look for a more permanent fix.

For now, the issues is back to quiet mode, since scratch is not longer blocked from editing.

Given the likeliness of reoccurence and having made actual progress, I will continue to poke at this in the interest of eliminating recurrence.
