### ISSUE TITLE
Make it possible to clone or copy events

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#583]
@burlexpo - tagging you to provide edits to my details here.  You keep mentioning this to me offline, but there is no ticket for it... now there is! :)

Let's make a way to clone events.  

**Events should be cloneable:**
- between conferences - I should be able to take an event from last year and clone a copy for this year.  Example:  Miss Mina's Tea Party, a special event, gets cloned from GBE 2015 to GBE 2016.  
- within a conference?  @burlexpo  is there a valid case for this???

**When cloning happens**
- child events are cloned too?
- date and time and room allocation is cloned?
- all details w/in the event (like the description, duration, etc) are cloned
- people-related allocations are NOT cloned - for example, volunteers booked into a volunteer position are not cloned.  Acts in a show are not cloned.  
- Exception - classes - Should classes be cloned?  Should the cloning include the teacher?

@burlexpo please answer things with a ? after them.

**Comment by bethlakshmi** [comment]
Assigned to burlexpo who can unassign himself when he gives us details.

**Comment by jonkiparsky** [comment]
Since we can already create events without cloning, I suggest that this is
relatively low priority - if it doesn't get done before the expo, we'll be
okay, so it should come after the things that we actually need before expo.

**Comment by burlexpo** [comment]
I'm not sure I agree.  It's more work than you may have realized.

Last year, several people (but mostly me) spent many. many hours figuring out the volunteer needs -- when shifts should be, how many people those shifts needed, the various locations, etc.  This is also true to a lesser extent for things like the Drop-in classes.  Then we (mostly me) spent many hours creating the events to populate that schedule, using the scheduling tool on the site which can be charitably described as 'unintuitive' to use. 

Trying to figure out how to back-translate last year's implemented list of volunteer events into some sort of format that we can glean the information from which will allow us to populate this year's volunteer schedule with times, descriptions, locations, volunteers needed, etc. seems like a bigger project with a larger chance of introducing errors than a software tool that allows one to click a checkbox to 'import' an event from a previous year to the current year.

Can you give me an estimate of how long you think something like this will take? I'm pretty easy on the format.  Ideally, I'd see a volunteer schedule present as a schedule with check boxes in any given event and a button below the schedule with says "Import Selected".  Something like this:
![screenshot 2015-11-29 13 41 37](https://cloud.githubusercontent.com/assets/5369404/11461976/217d619c-96db-11e5-98c5-8937ca1bad9d.png)

That said, I'm not married to the format; I just want to be able to get last year's events and volunteer shifts into this year's schedule where I can reuse, edit, or delete them as necessary.

**Comment by jonkiparsky** [comment]
> Can you give me an estimate of how long you think something like this will take?

No. Sorry, but no, I can't, and nobody can, because estimation in terms of hours is simply guessing. 

If we wanted to be able to plan things, we would have started estimating tickets months ago, and if we'd done that then by now we'd have a pretty good idea of how much work we can do in a sprint, and we could reasonably promise a particular batch of work in a particular chunk of time. But we didn't do that, so we can't, and that's that.

**Comment by burlexpo** [comment]
"No. Sorry, but no, I can't, and nobody can, because estimation in terms of hours is simply guessing."

Yes, it's educated guessing -- and people do it all the time.  Some with more skill and accuracy than others.

I need to balance the limited resources I have (programmer's time) vs the needs of the business.  If I can't have an idea of how long something might take, than I'm working blind.  Something that is low priority but won't take very long, might get kicked up the queue because it won't take very long...

If you don't want to bother giving me some input, than we'll just continue crashing along as we have been.

**Comment by jonkiparsky** [comment]
You're working blind because we chose not to make it possible to plan. I'm not going to pull numbers out of my ass now just because you're starting to regret that decision. 
If this is a "high priority" item for you, put that label on it and and clarify the questions in the spec and we'll figure out a way to get it done.

**Comment by burlexpo** [comment]
On 12/10/15 1:05 AM, Jon Kiparsky wrote:
>
> You're working blind because we chose not to make it possible to plan.
>
And change is impossible because everything we do is carved in stone? 
C'mon, Jon....
>
> I'm not going to pull numbers out of my ass now just because you're 
> starting to regret that decision.
>
No, you're not going to give me the tools I need because you don't want 
to be held accountable to an estimate.  Which is fine, but own up to the 
decision and don't put it on me.
>
> If this is a "high priority" item for you, put that label on it and 
> and clarify the questions in the spec and we'll figure out a way to 
> get it done.
>
No.  *That* is a bullshit way to do things.  I don't know if it's a high 
priority because I don't know what the "cost" is.  Some mornings, a cup 
of coffee is a high priority, but if that cup of coffee is going to cost 
me $200 instead of $2, or I'm going to need to wait an hour for it 
instead of 5 minutes, than it's a low priority.

**Comment by bethlakshmi** [comment]
@burlexpo - I'm staring on this as the most flexible option for a copy operation.  When I'm done, I hope to have:
- copy for any type of event
- a copy that lets you pick the conference & day for making the whole event collection (say, for a staff area)
- a copy that lets you pick a target parent event in the case where you've already made one (like shows)
- the option to NOT copy sub-events.

It won't cover editing of things that are not currently editable (rehearsal slots).  I"ll want to do that under a different ticket.
