### ISSUE TITLE
No indicator for costume submission

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#609]
When you save a draft costume bid there's no indication on "Your Expo" that it's a draft and has not been submitted.  

When you submit a costume bid, there is no "success" message and the only indication that it has been successfully submitted is that there's now a 'no decision' text next to the name of the costume.  This is too subtle for most of our users.

Ideally, when you submit a costume bid (or any bid) successfully, you should get some sort of 'You've successfully submitted your thingy for consideration" message -- it could be a page the user is redirected to, a pop-up, or an email.

As a next best solution, can we change the bid status displayed on Your Expo on a costume which has been successfully submitted from "No Decision" to "Submitted.  No Decision"?

**Comment by bethlakshmi** [comment]
Some questions:

- the Costume Display proposal is showing on my expo page - see picture - is it showing on yours after you submit a bid?
- the text shown in the costume display bid is slavishly consistent with class bids.  - how about if I make both of them slavishly consistent with Act Bids?  (I do love the consistency...) - they show:

 - Betty Tests Show Cues - Accepted
   - View act
    - View/edit Act Tech Info and rehearsal schedule
 - Testing 2016 - Not submitted
   - View/edit this act bid

- Then also make sure that if it's submitted I show 

Bid Title - Submitted. << state of acceptance >>

We do have tickets for both 
 - show a message to the user when something informational has happened. #436 
 - email acknowledgements #363 

I know these are persistent gaps in functionality - but instead of reiterating, can we figure out how and when to escalate the existing tickets?

--------

Effortwise changing around the text on the Your Expo page can be done quickly and low risk.
The other two needs deserve and have separate tickets that I'd rather escalate in priority than handle here.

**Comment by bethlakshmi** [comment]
How do any of these things rank compared to the current Betty assignment list?  Does this block deploying Costume Bids?  If so, it's a 'high' IMO.

**Comment by burlexpo** [comment]
"the Costume Display proposal is showing on my expo page - see picture - is it showing on yours after you submit a bid?"

What picture?

Yes, I see costume bid activity in my personal pane.

**Comment by bethlakshmi** [comment]
Sorry... eventually I realized from context that you are seeing this:

![screen shot 2015-12-13 at 8 56 35 am](https://cloud.githubusercontent.com/assets/4542707/11767451/08579ea2-a17c-11e5-95f8-3718c54608eb.png)

Right?

**Comment by burlexpo** [comment]
Yes, that is what I am seeing. 

And this should not block deploying the form.

**Comment by bethlakshmi** [comment]
@burlexpo - I am closing because I think this is covered by other work - we have a submit message that happens now on costume draft save and on submit.
And when current pull requests are done, we'll also send email on state change when bid is accepted.
