### ISSUE TITLE
Process offers gathered through http://burlesque-expo.com/conference/volunteer/

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#644]
Take a look at https://github.com/bethlakshmi/GBE2/wiki/Volunteer-as-panelist-%28or-teacher%29
and see if you can implement it.

**Comment by bethlakshmi** [comment]
https://github.com/bethlakshmi/GBE2/wiki/Volunteer-as-panelist-%28or-teacher%29

Is the original use case writeup. 

Use Case 3 is the relevant case.  The other 2 cases are implemented already.

**Comment by burlexpo** [comment]
@jonkiparsky -- I'll let you know when I've reviewed the use case document, but it should be less than 48 hours.

**Comment by bethlakshmi** [comment]
This is not a report as in "in the reports view" guys, this should be a "review panelist" like the other bid review screens.  The reports views are totally passive, this is quite active (coordinator can change state and assign candidates to schedule).

**Comment by bethlakshmi** [comment]
Some quick ass notes:
- volunteers for the conference = moderators, panelists, teachers
- Class coordinator is the relevant privilege (it is not a new privilege)
- Conference Volunteers is the database storage system combined with Class Proposals.
- The business logic involves actually *creating* the class event, and then scheduling it, because we would need a scheduled event to assign volunteer panelists to it.
- we need more discussion before taking this on - the use case is NOT clear....

**Comment by burlexpo** [comment]
Putting this here for later.
The BHOFWeekender Volunteer page is at http://bhofweekend.com/support/volunteer/
The Volunteer application is at https://docs.google.com/forms/d/1nln79mTI4NZjfl1QJG5r18gKyhTmV5xphg0Bq7tXXV8/viewform

**Comment by bethlakshmi** [comment]
deprecated, just removed this feature
