### ISSUE TITLE
Only two levels of menu?

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#656]
Hey -- 

If you look at the menu tree on the live site, you'll see I've created a third level menu to allow people to directly access info on a show they want.  That is, the "Shows & Events" menu looks like this:

Shows & Events
----- Special Events and Parties
----- All Shows
---------- The Rhinestone Revue
---------- The Bordello
---------- The Main Event
---------- The Sunday Showcase

All of the menu items are published and have "visible in navigation" turned on.  But, if you pull down the **Shows & Events** menu, the last four (the submost level of menu) are not there.

Am I doing something wrong? Or is there some setting in the CMS which says "only display the X levels of menu" -- because I'd like to display this level.

**Comment by bethlakshmi** [comment]
Looking now... I think this is a code change for me... didn't know you needed multilevels.

a few questions:
1 - how many levels would you like?
2 - how fast do you need it?

**Comment by bethlakshmi** [comment]
Bleh.  Quitting for the night.  I found out that:
1 - there is a setting that i turned off in Django CMS that limits child menu availability.  I basically said to it when I set it up "make there be 1 level of depth" and I can pick any number.

2 - however, the js we are using (bootstrap) does not support multi level menus right out of the box, so when django-cms gives all the menu stuff, our existing HTML + JS + templates don't display it - it looks like an expandable menu and then does nothing.  Blech.

I will play more tomorrow as the next top priority since it is marked high.  It should not be too invasive, once I figure out how to make submenus.  I have some good sites pointing me in the right direction.

**Comment by burlexpo** [comment]
Thanks.  There are workarounds (like putting menus on pages by hand), but I'd rather not do that.

**Comment by bethlakshmi** [comment]
Fix is ready, pull request is pending.  it was a lot of fussy CSS and JS in the end.
What it boils down to is that the example menu code I originally used from Django CSS did not properly provide the functionality - there was some JS missing and the CSS worked, but in an ugly way.
