### ISSUE TITLE
Automated Volunteer Notifications

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#665]
*Question* We require volunteers to have logins, right? If we do, than go ahead with this issue as writ.  If not, I'll need to re-write the form letter.

**Desired effect:**  When a change is made to a user's volunteer scheduled (i.e., they are scheduled for a shift or removed from a shift), we automatically send an email to the user with the following message:

> Dear [username],

> Thank you for participating in The Great Burlesque Exposition! An update has been made to your 
volunteer schedule.  Your current volunteer schedule is listed below; you can also check your schedule at anytime by logging in to the site and looking at your personal page.

> (then personal schedule of volunteer shifts goes here.  Anything else -- like rehearsals, teaching slots,  etc. -- is *not* listed.  If that's hard to do and it's much easier to just list their complete schedule, that's 
fine, just replace "Your current volunteer schedule is listed below" (above) with "Your current schedule  is listed below").

> Please try to report for each volunteer shift a few minutes before it begins.  If for any reason you will not be able to make the commitments on your schedule, please contact us *immediately* at  *info@burlesque-expo.com*.  In case of emergency during the BurlExpo, you may call us at (617) 869-2000.

> Thank you for being part of The Great Burlesque Exposition!

**Comment by bethlakshmi** [comment]
Yes, we totally require that volunteers have user accounts and profiles.  They don't need to have personas.

This extends a pattern of emailing and the more I think about it, the less I want to hard code even more big blocks of text in a place that @burlexpo can't update them.  Also - I want to do this a tad bit thoughtfully, because emailing the human fits with the "gbe" side of things, but managing the schedule ties into the scheduler side, and volunteer assignment happens in two places - event schedule setup (scheduler) and volunteer bid assignment (gbe).

So... with that in mind, here's a very sketchy design proposal, @jonkiparsky and @BenignCremator - I'd love your feedback before Tuesday, since I will likely start on this while I'm on a place to LA tomorrow.

1 - create a new function in gbe functions - since that's where our other email contacts are.  Function would take the user profile that is being scheduled, and then use a template to render an email message to the user that comes from a static email address.

2 - use this function in volunteer bid change state in gbe/views.py - the function volunteer_changestate

3 - use this function in scheduler when volunteer assignment happens - scheduler/views.py - allocate_workers.  - which means that scheduler will have to call gbe/functions.py for the new function from step 1

That seems like the best way to handle this... 

Longer term, I'd like to find a way to take the template used for the email message and put it in the DB, so I don't have to get hard coded text from Scratch, but I'll advocate for that after the expo.

**Comment by jonkiparsky** [comment]
Yes, that seems reasonable for now. Don't do more than the minimal on this,
since it's likely to be replaced once #436 gains focus.

**Comment by bethlakshmi** [comment]
I pondered this more and saw a flow problem:
1 - volunteer coordinator assigns the volunteer to some events
2 - the event has a conflict and the coordinator is notified... however there's no way to know whether or not this is intentional, so the volunteer gets sent an automail.
3 - the volunteer coordinator gets the notification of conflict and goes to fix it.  Volunteer info is updated...
4 - volunteer gets another email with fixed conflicts,

The volunteer is now wondering if schedule from step 2 or schedule from step 4 is accurate.

Fix I agreed on w. @burlexpo - give up on automailing on a per-assignment basis.  Instead, provide a way to let the coordinator and/or schedule maven mail to ALL volunteers that currently have a schedule, a list of schedule assignments. 

Ideally the coordinator/maven could enter the text themselves that comes before and after the schedule.  We don't even need to persist that text, we could mail the user who made it a copy.  Chances are, the author wants something new and different each time, since they mail the list of volunteers multiple times reminding them over and over so they don't forget (they do forget.  All the time.)

**Comment by jonkiparsky** [comment]
This is actually not such a big deal. Send an email saying "you have a
schedule update, please check your page". Done.
