### ISSUE TITLE
Export "All" calendar as Guidebook .csv

### ISSUE THREAD

**Issue by bethlakshmi** [bethlakshmi/GBE2#666]
Guidebook has a format for importing schedule data.

Here's the guide, change *.txt to *.csv, git hub doesn't allow CSVs

[Guidebook_Schedule_Template.txt](https://github.com/bethlakshmi/GBE2/files/85956/Guidebook_Schedule_Template.txt)

We should be able to offer a scheduler thing that does "export calendar for conference_slug" and gives a csv that guidebook will take.

**Comment by burlexpo** [comment]
That's awesome.  It will save Mina a ton of time and reduce the likelihood of introducing human error.

**Comment by burlexpo** [comment]
*Here's the guide, change *.txt to *.csv, git hub doesn't allow CSVs*

? The format you gave is ".txt" already.

**Comment by bethlakshmi** [comment]
Change the *.txt that is there already

TO *.csv.

The file appears as a text file, it is REALLY a csv file.

**Comment by burlexpo** [comment]
Did this ever happen? Mina has offered to make the Guidebook happen.

**Comment by burlexpo** [comment]
@bethlakshmi  - can this happen? If it doesn't happen ASAP, then let's push it to next year and Mina will do it by hand.

**Comment by BenignCremator** [comment]
Have code that generates correct csv files from the shell.  Now working on hammering it into a view, and the url reference.

**Comment by BenignCremator** [comment]
Have gotten export working for Guidebook!  Looks pretty good, with one potential issue.  Guidebook template shows using 'AM' and 'PM' instead of 'a.m.' and 'p.m.', but Django formatting uses 'a.m.' and 'p.m.'.  Checking if Guidebook can deal with that.  Also, iCalendar export is having time zone issues.   Or the scheduler is.  Namely, times exported to an ics file are in UTC, and GBE is not properly setting the time zone, so importing an ics file shifts the start and end times by -5 hours from expected time.

**Comment by BenignCremator** [comment]
Have temporarily removed exporting iCalendar format for now.  It will return once I figure out how to get the time zones to work from settings.  Until then, will work on tests.

**Comment by bethlakshmi** [comment]
Cool!

How is this going?

**Comment by BenignCremator** [comment]
On 12/14/2016 08:56 PM, bethlakshmi wrote:

> Cool!

> How is this going?

Not bad.  Main functionality, per ticket, is done, with one issue. 
Django localization outputs time as 'a.m/p.m.' and Guidebook's example 
shows 'AM/PM'.  Could not find on their website if their parser can 
parse 'a.m./p.m.'.  If not, dropping in a replace rule is dead simple. 
PEP8 is also done. Only thing outstanding is tests for the new 
functions/views.  Also have iCal output working, with one caveat. 
Working on this has exposed that we have been setting all times in UTC. 
So iCal output puts the start of shows at 3pm EST.  Guidebook is not so 
smart that it works messes up so easily.  At any rate, hope to get the 
tests sorted out tonight, maybe tomorrow.

Hunter

**Comment by BenignCremator** [comment]
Ok, latest commits have working tests, and tweak the output for Guidebook, so, ticket should be done.  YAY!  However, 8 seemingly unrelated tests now fail.  ???  Looking deeper into the issue.  First, checking that these tests were not failing when I began coding, then testing if removing my code fixes the problem.  Should have this sorted by tomorrow afternoon.

**Comment by BenignCremator** [comment]
Ah ha!  Forgot that I had tweaked the time zone settings in settings.py to test the problems with iCal output.  This was causing eight tests, which hard code test times in UTC and check for literal output, to fail.  Since that tweak did not get checked into github, do not need to worry about it.  Issuing PR.

**Comment by BenignCremator** [comment]
New code to fix import into Guidebook.  Purges unprintable chars, replaces noon and midnight with more useful times, fixes issue with filename being based on current not requested conference.  See PR 930.
