### ISSUE TITLE
Upgrade django to supported version

### ISSUE THREAD

**Issue by jonkiparsky** [bethlakshmi/GBE2#743]
This ticket tracks work towards getting the codebase compatible with a current django release (1.8 or 1.9)

**Comment by bethlakshmi** [comment]
Pulled the In progress because this is on hold.
We have a PR #904  for the upgrade of Django 1.7 for Django CMS libraries.  It's waiting to be merged onto the GBE upgrade to Django 1.7 (GBE-806, aka #806 ).

Right now, that work is on hold, if @jonkiparsky has time, he would be welcome to pick it up.  If this rests on me, then it waits until March 2017 when the 2017 expo is over.

This ticket could also use additional work for a Django CMS 1.8 ready version, and even a Django CMS 1.9.  These updates could be developed out of band from the GBE upgrade process, so they are ready when GBE needs it.

If these were a more hierarchial ticket system, this ticket would be an epic.
