### ISSUE TITLE
Create a mobile-friendly version of the site

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#819]
N.B.: This could be broken into two tickets.  First ticket -- evaluate and select a mobile site solution; 2nd ticket -- implement and test solution.

Jumping off of UX input collected by Carolyn, attendees are looking for easy, mobile access to select information.  People do **not** need to be able to bid acts or classes on the mobile site; it's a toss-up as to whether they should be able to volunteer or become a vendor.  

People **should** be able to 
- ~~see their personal schedule~~
- see the schedule for the conference with class descriptions, locations, and teacher bios (maybe not pictures)
- ~~see the schedule of shows with performer bios (maybe not pictures)~~
- see the schedule of special events (parties, drop-in classes, fashion shows, interviews, etc.) with locations

There are some mobile-related Django packages at https://www.djangopackages.com/grids/g/mobile/

**Comment by bethlakshmi** [comment]
@burlexpo - can we break this into 2 tickets:

1  - we display a personal schedule for logged in participants - and for this I have the following questions - if all things were equal, is it better to:
    - use a calendaring API to let them invite themselves to their GBE commitments, so it shows up in a mobile phone calendar
    - have a nice mobile-ready display in GBE using a common mobile web browser

2 - display public schedules (the equivalent of the 3 schedule types today) in a mobile way, and is it preferable to:
   - improve the way we sync to the mobile calendar app you've been using & also put a big, obvious redirect on the website (maybe it detects that this is a mobile device and then says "hey do you know about our cool mobile hosting - click here...")
  - OR - have it display in a mobile friendly way on the main site.

Also - I think we go with "all mobile friendliness is on GBE web pages" - then we need a 3rd ticket which is - make a mobile friendly menu option & home page - because people won't use our work if they can't navigate to it.  

And I'd like us to define our mobile targets for testing.  Would it be a current version of Iphone and a current version of some Android?

**Comment by bethlakshmi** [comment]
#1115 closes all the areas mentioned here
