### ISSUE TITLE
Changes to http://burlesque-expo.com/volunteer/bid/ #2 (Rank areas of interest/Allow "no" list)

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#822]
On http://burlesque-expo.com/volunteer/bid/ 

Change the question labeled "Interests"  to allow user to rank areas of interest in order of appeal.  Replace the existing checkboxes with one drop-down list per interest.  All drop-down lists on this page offers the same options:

- [blank]
- Not interested
- Slightly interested
- Neither interested nor disinterested
- Somewhat interested
- Strongly interested

- Users can rank multiple interests with the same values (i.e., both Art Show and Conference Staff can be given a value of "Slightly interested")
- Users can leave interests blank to indicate that while it doesn't interest them, they are not opposed to doing it

*Add popover help text* which reads "We appreciate all our volunteers. Please rank the different areas according to your level of interest.  We will do our best to accommodate all requests, but please realize that you may get assigned to areas which are not your first choice".

**Comment by jonkiparsky** [comment]
Data Migration: existing positive interest -> 3
Unchecked -> 0

**Comment by bethlakshmi** [comment]
Umm... Jon's note confuses me.

@burlexpo - please clarify...
Does "3" (ie, "currently checked in the old data") = Somewhat interested
And "0" (ie, "not currently checked in the old data") = Not Interested

Or does "0" = blank?

I'd like to advocate for "0" = Not Interested, as that's what a checkbox format implies to me.

Also - what do we want the default to be - when a new volunteer first loads the screen?  All fields blank, all fields at a "Neither Interested or Disinterested"?

And - is it important that I yell at them in any collective case - for example, if they show no interest in anything at all?  (all are < "Somewhat Interested") or if they leave all blank?

Yelling at them is more work than not yelling at them, but not radically more (maybe 1-2 Fibonacci points, so I've got some wiggle room...)

**Comment by burlexpo** [comment]
I believe the answers have numerical values as follows

0 - unchecked
1 - Not interested
2 - Slightly interested
3 - Neither interested nor disinterested
4 - Somewhat interested
5 - Strongly interested

So, 0 = blank.  
--------------------------
The default is all fields are blank

And I think they have to have at least one field of at 4 or higher to submit the bid.  Otherwise, give them an error message and don't even let them submit it.

**Comment by jonkiparsky** [comment]
> And I think they have to have at least one field of at 4 or higher to submit the bid. Otherwise, give them an error message and don't even let them submit it.

This is likely to cause problems. Unless it's really necessary to police this state (why?) I would suggest allowing people to save without interests. (show a warning, but accept the save)

**Comment by burlexpo** [comment]
Having people submit bids without interests is also likely to cause problems on the other side.  Is there a reason why we should allow people to submit a volunteer bid that says the equivalent of "I don't want to volunteer"? It seems likely to cause confusion amongst reviewers and users.

**Comment by jonkiparsky** [comment]
Yes, there are various reasons why we shouldn't enforce state constraints that we don't really care about. The main one being, we don't really care about them. If someone wants to create this state, there's probably a reason for it. 

(I think the problem you're actually trying to solve is that we don't allow people to edit these objects, but that's a self-inflicted wound)

**Comment by burlexpo** [comment]
> If someone wants to create this state, there's probably a reason for it.

Where "this state" is submitting a bid which says "I hate all your volunteer opportunities"? Yes, the reason could be a) they don't understand how the system works, or b) they're just being a dick.

> (I think the problem you're actually trying to solve is that we don't allow people to edit these objects, but that's a self-inflicted wound)

Not a wound, a design choice.  If we allow people to edit these forms once they're submitted we open up a whole can of nightmare for the people who are trying to do the scheduling of volunteers.

**Comment by jonkiparsky** [comment]
Whatever. Your funeral.

**Comment by burlexpo** [comment]
Dont sulk, Jon.  If you have a reason other than "I don't like it", I'd love to hear it.  But all you seem to have is "I don't like it" and that's not enough for me on this -- especially since I think this code is done already and waiting for review.

**Comment by jonkiparsky** [comment]
Okay, here's the long version:

You're right - I don't like it. I don't like it because it constrains users in a way that is not useful and is likely to run up against some state that the user thinks is reasonable and we don't really care about, so it puts your users up against your UI for no good purpose. 

The most important of these cases are the ones we can't anticipate. Users are not machines, they will always come up with things that you can't anticipate but which will make sense. Unless there's a very good reason to block those states (ie, threats to data coherence) it's usually a bad idea to block them. A volunteer state that sorts to the bottom of the pile and stays there is not a threat to data coherence, it's just a weird state that you look at and learn something from. 

One particularly salient example that we can anticipate is the user who is interested in volunteering but doesn't really care what they do. This user might select 3 ("Neither interested nor disinterested") for all volunteer areas. For that matter, they might select 2 ("Slightly interested"). This will fail, annoying your user for no useful purpose. 

Or, as you suggest, the user might want to volunteer but actually not want to do any of the things you offer. This should tell you something - specifically, it tells you that some user is willing to help but you haven't come up with a way to use that resource. That's a volunteer that you probably want to get in touch with and figure out what they actually want to do.

Or, we might come to our senses and require a Volunteer object for all booked volunteers (this would clean up a lot of problems in the code and increase development velocity on related tickets). In this case, you would sometimes need to be able to create a Volunteer object on behalf of a user, but it wouldn't make sense to select preferences for that user. 

Those are just the obvious cases that come to mind. Your users will probably come up with others. 


As for the absence of editing for submitted volunteer forms, this is just nuts. If someone is offering to volunteer, and they're telling you when they're available, why on earth wouldn't you want to have their most up-to-date information? After all, people don't change their availability to inconvenience you. They change their availability because the time they're available changes and it does you no possible harm to know when this happens. Similarly for interests - I don't know what makes someone change their interests, but if they actually do want to change this then you surely want to know about it. 

A user's schedule preferences only matter to you at the moment when you're scheduling them. Between the time they create the preferences and the time you're using them, it doesn't matter what they do with them, and in fact you'd prefer that they update them to reflect their actual preferences. 

The negative outcomes from your approach are, (1) lost potential volunteers, who don't sign up because they don't happen to know their schedule for next February at the moment it occurs to them to volunteer, (2) aggravated volunteers who were assigned based on obsolete data and turned up to their shift, (3) absent volunteers who were assigned based on obsolete data and skipped their shift, or (4) wasted staff time changing volunteer commitments that should be edited by the volunteers. This is a lot of loss. 

By way of a reality check, I actually maintain a system that solicits volunteer commitments from a much bigger and more volatile group than you're dealing with - our judge pool - and I can tell you that the nightmare you envision does not arise. I honestly hate to think of what a mess we'd be dealing with if we didn't allow judges to update their availability as their circumstances changed, but fortunately we'll never find out because we would never try that experiment.

**Comment by burlexpo** [comment]
Ok -- thanks.  That's actually some useful information, coherently presented.  In some cases your experience isn't as relevant as mine is (i.e., with other volunteers working on a different type of project), but at least I get to see where you're coming from.

I don't think we're going to let volunteers adjust their bid once it's submitted unless someone tells me that it's a 5 point fix, because I don't want to spend resources fixing things that aren't actually not working.  

That said, if we can set things up so that if someone tries to submit a volunteer bid in which every preference is a 3 or lower they get a notification saying "Hey -- your Volunteer Application doesn't actually say what you *want* to do, it only tells us what you *don't* want to do.  Are you sure you meant to do that?" or something similar, I'm fine with that.
