### ISSUE TITLE
Events should have default locations

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#833]
*Current Functionality* You create an event, you schedule a session of that event.  In the process of adding the session you can specify features of that particular session (i.e., location or teacher).  You have to do this for every session added.

*Observation* Many of our events (especially volunteer shifts) all happen in the same place.  For example, all Registration Desk shifts happen at Registration, all Merch Table shifts happen at the same location, etc.

*Desired Functionality* When creating an event, have access to the pulldown menu of locations so the creator can specify a default location.  When adding a session of that event, the location can be changed (but if it's not, it stays with the default).

**Comment by bethlakshmi** [comment]
Tech details:

On this page - http://localhost:8282/create_event/GenericEvent
there would be an additional field for "Location" that gets set at create time.

On this page - http://localhost:8282/scheduler/create/GenericEvent/548
the default location is populated in the location field

On this page - http://localhost:8282/scheduler/edit/GenericEvent/2528
there is no change at all - because it's editing an existing session and the default no longer applies.

Assumption - the default is only set at creation time.  The rest of the time (editing/creating the session), the setting is the room allocated to the event.

Assumption - the default being set does not mean the location is "booked" until it's booked for an actual session with a start time and an end time.
