### ISSUE TITLE
Separate Forms from introductory text; make forms a plug-in (fashion_faire)

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#852]
Most of our forms use the format of several paragraphs of introductory text, followed by the form itself.  Currently, the introductory text and the form are all one piece, which requires a programmer to make edits to the introductory text. 

Goals:
- Remove introductory text from above form and put into a CMS window.
- Allow forms to be inserted into pages as a plug-in (like an image or a email sign-up form).

**Comment by bethlakshmi** [comment]
This is something I experimented with back in the Django-CMS integration days.

It is doable, but a bit of an integration adventure.  Django-CMS has plug in creation instructions here:
http://docs.django-cms.org/en/release-3.1.x/how_to/custom_plugins.html?highlight=plugin

The gist is, there's 3 things to write:
- editor - what the admin tells us when they want to stick the plug in on the page
- publisher - what the plug in does to marshall data and render the template when it is stuck on a page
- template - the django template used by the plugin (which we can reuse from existing templates, I believe).

**Some thoughts for scoping:**
- that we take on only 1 bid form for the first integration, vendors or class proposal may be the easiest, because they are a simple form with very little business logic.  Classes (the bid-class) requires a persona, Acts requires a persona, Costumes uses persona, volunteers has lots of data to marshal to build the form.
- that the ticket includes publication instructions so we can follow a defined process for similar forms.

**Question on complexity**
- do we mean the creation part (a blank form with no user-entered data in it)?
- or do we mean create AND edit?

This one is heavy on the opportunity to build lots of comfort with Django-CMS....

**Comment by jonkiparsky** [comment]
Definition of done:
/fashion_faire/ page has a plugin to include vendor display template and editable text box.

**Comment by burlexpo** [comment]
@bethlakshmi looks like you've successfully done this for the Fashion Faire page.  How hard would it be to implement for some of the others?

**Comment by bethlakshmi** [comment]
not hard, as I did it... we just need to define what "others" means - for example, I assume you mean - every bid page.

Do you also mean:
intro text on teacher biography lists?
or on other lists?
or on the material that comes when acts or vendors submit an act/vendor bid?
Other places I have not thought of?

as I did in fashion faire, it's pretty easy.  more elegance takes more time...

**Comment by bethlakshmi** [comment]
Django CMS is not that easy to use - getting more in bed with it this way is not our best strategy
