### ISSUE TITLE
BUG: Class Submissions not showing up on Class Review Page

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#901]
TAG - @bethlakshmi @jonkiparsky 

Scarlett Letter (http://burlesque-expo.com/profile/landing_page/30) has submitted a bunch of classes, that aren't showing up on the Class Review page (http://burlesque-expo.com/class/reviewlist) for either me or for Red Velvet but they **are** showing up as submitted on Scarlett's landing page.

My quick guess is that it has something to do with the re-submit old classes function.

Can someone jump on this ASAP?

**Comment by jonkiparsky** [comment]
Taking a look

**Comment by jonkiparsky** [comment]
@burlexpo just to make sure we're on the same page, can you give me the titles of one or two of the classes that are in the problem category?

**Comment by jonkiparsky** [comment]
NM, think I found one. http://burlesque-expo.com/class/edit/772 "Body of Work"

**Comment by jonkiparsky** [comment]
Looking at the admin, I see that these are not marked as "submitted", which explains why they're not showing up on the class review list. 

When I masquerade as Scarlett, I'm not sure what should make me think they've been submitted, but I do see that the edit class view has a "Submit for Approval" button, which I wouldn't expect to see if the class has been submitted already. 

What I don't know at this point: has Scarlett gone through the submit flow for these since she cloned them? If she has, then the submit flow is borken, and needs fixed. If not, then this is behaving as expected, and she needs to submit them. 

Back to you @burlexpo

**Comment by burlexpo** [comment]
Yup, you're right.  It says _click to edit_ not _submitted_.  I wonder how we could make that clearer; Scarlett's not a dummy and it took me looking at it a second time to realize the mistake.  I'm closing this.
