### ISSUE TITLE
Automate linking rehearsals to shows

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#919]
Currently, associating rehearsal slots with shows is a manual process and is done by @bethlakshmi .  **Goal** Create a privileged button or command that does this automatically.

More details:

- a "Rehearsal Slot" (aka a GenericEvent with the type of Rehearsal Slot) needs to be linked to it's Show via the Event Container (the show is the parent, the rehearsal slot is the child).  This is like volunteer slots.

- Volunteers slots have GUI that let a scheduler make the slot as a part of setting up the bigger event (the show, the staff area, etc). Rehearsal slots don't.

Ideas:

1 - make a way for the user to create a rehearsal slot the same way they create a volunteer slot, picking a max number of acts, instead of a max number of volunteers.

2 - chain into #679 and build an automatic number of volunteer slots with a fixed number of acts when a show is created.

3 - let the user just spec out the following parameters:

  - number of slots
  - time window for slot (1 hour, 1/2 hour, etc)
  - start time of rehearsal block 
  - number of of acts per slot

So.. if the user creates 4 1/2 hour slots, of 10 acts each starting at 2:00 PM, the system creates four slots at 2, 2:30, 3, 3:30, each with 10 acts, allowing 40 acts total to rehearse over the course of 2 hours.  And it would inherit the staff lead of who ever is the lead for the show.  

Already, we have rehearsal slots be editable in the scheduler, this would not change any of the way that rehearsal slots can be edited.

**Comment by bethlakshmi** [comment]
#1238 + copy events is as close as seems reasonable

**Comment by eclecticmagpie** [comment]
This reminds me of a related volunteer issue that you may or may not be
able to accomodate:

Ideally, the Playback and FOH engineers for a show should also be the ones
present for rehearsal, so that the notes they are looking at are their own,
and they also have the benefit of direct experience to help them interpret
those notes.  It's more important for the Playback engineer to be the same
than the FOH engineer.  In order of preference:

1 BOTH
2 Just Playback
3 Just FOH
4 NEITHER

Currently this is managed by hand.  It's not that big a deal it just struck
me that it may be susceptible to partial automation.


Mike Bergman
www.prospecthillforge.com
www.vintagedancers.org/teadance
www.isebastiani.com
reply-to: eclectic@mit.edu
