### ISSUE TITLE
Acts cannot be withdrawn

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/GBE2#981]
The bug *may* be "Act bid status cannot be changed", but I'm not sure.

I went to http://burlesque-expo.com/act/review/710
I marked it as "Withdrawn" using the pulldown menu
I clicked submit
I was redirected to http://burlesque-expo.com/act/changestate/710

Going back to http://burlesque-expo.com/act/reviewlist, the act ("Duende") still shows as Accepted.
Looking at the list of performers for the Sunday Showcase (http://burlesque-expo.com/scheduler/details/603/) the act is *not* there, so half of things are happening.

**Comment by bethlakshmi** [comment]
Found it.
The problem was that we added logic to make sure that acts are uniquely named (in terms of title) to avoid users making copies rather than editing drafts.  That fix must have gone in after Nov. 7 because many acts prior to that date have duplicate titles.

When we have duplicate titles, the form verification says that the form is "invalid" because the verify_unique check fails.  I never expected to have errors on this form (everything is a drop down) so the error reporting is particularly cheesy.

We did send the user the email, and pull the show assignment, but the state didn't change.

I fixed this manually by:
- removing all duplicate acts for this year.
- checking all act states that had email sent (so, for the last month or so) 
- making sure the state was fixed.
